<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <!--.NET 9 packages. Most of them will work on .NET 8. If you need to, make the updates here individually.-->
  <ItemGroup>
    <!-- Static code analysis -->
    <PackageVersion Include="SonarAnalyzer.CSharp" Version="10.15.0.120848" />
    <!-- Application -->

    <!-- Infrastructure -->

      
    <!-- Api -->
      <PackageVersion Include="Microsoft.AspNetCore.OpenApi" Version="10.0.0"/>

    <!-- ArchitectureTests -->
  </ItemGroup>
</Project>